export default function Landing(){return(<main>
<section className="section" style={{background:'linear-gradient(135deg,#f8f9ff,#eef1ff)'}}>
  <div className="container" style={{display:'grid',gridTemplateColumns:'1.2fr 1fr',gap:16,alignItems:'center'}}>
    <div><h1 className="h1">Trade What You Have. Get What You Want.</h1><p className="muted" style={{fontSize:18}}>Barter skills, goods, and services with NYC locals. No cash. Just connection.</p><a className="btn" href="/profile" style={{marginTop:12,display:'inline-block'}}>Create Your Profile</a></div>
    <div className="card" style={{height:260}}><div style={{position:'relative',width:'100%',height:'100%'}}><span style={{position:'absolute',left:28,top:28,width:120,height:120,borderRadius:999,background:'#4C84FF',opacity:.25}}></span><span style={{position:'absolute',left:160,top:8,width:84,height:84,borderRadius:999,background:'#00D8A4',opacity:.35}}></span><span style={{position:'absolute',left:220,top:140,width:48,height:48,borderRadius:999,background:'#4C84FF',opacity:.55}}></span></div></div>
  </div></section>
<section className="section" style={{background:'var(--bga)'}}><div className="container"><h2 className="h2">How Trada Works</h2><div className="grid3"><div className="card"><b>1. Create Your Profile</b><p className="muted">List what you <b>offer</b> and what you <b>want</b>. Choose <b>Strict</b> (exact) or <b>Open‑Ended</b> (flexible).</p></div><div className="card"><b>2. We Match You</b><p className="muted">We connect you with New Yorkers who want what you offer — and offer what you want.</p></div><div className="card"><b>3. Make the Trade</b><p className="muted">Agree to a swap. Chat, meet up, exchange. No payments. Just mutual value.</p></div></div></div></section>
<section className="section"><div className="container"><h2 className="h2">What NYC Users Are Trading</h2><div className="card"><p>🍜 Host a 3‑course Korean dinner ↔ moving help on Saturday</p><p>🎫 Two concert tickets ↔ resume help + dog walking</p><p>📸 Portrait session ↔ espresso machine repair</p><p>🧠 Logo design ↔ two hours of business coaching</p></div></div></section>
<section id="waitlist" className="section" style={{background:'var(--bga)'}}><div className="container"><h2 className="h2">Join the Waitlist</h2><p className="muted">We'll invite NYC users as matches are found.</p><div className="card"><div style={{maxWidth:900,margin:'0 auto'}}><iframe src="https://tally.so/r/mO2k7Q?hideTitle=1" width="100%" height="500" frameBorder={0} title="Join the Waitlist"></iframe></div></div></div></section>
</main>)}